---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: activemq
    groups:
      - activemq_group
    image: ${MOLECULE_DISTRO:-idealista/jdk:11.0.18-buster-openjdk-headless}
    pre_build_image: true
    privileged: false
    exposed_ports:
      - 8161/tcp
      - 61616/tcp
      - 1099/tcp
    published_ports:
      - 0.0.0.0:8161:8161/tcp
      - 0.0.0.0:61616:61616/tcp
      - 0.0.0.0:1099:1099/tcp
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
verifier:
  name: ansible
