---
dist: focal
language: python
python: "3.9"
os: linux
services:
  - docker
before_install:
  - echo '{"default-cgroupns-mode":"host"}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=idealista/jdk:11.0.20-bullseye-openjdk-headless
    - MOLECULE_DISTRO=idealista/jdk:11.0.18-buster-openjdk-headless
script:
  - pipenv run molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
